//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlinktConfig) DeepCopyInto(out *BlinktConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlinktConfig.
func (in *BlinktConfig) DeepCopy() *BlinktConfig {
	if in == nil {
		return nil
	}
	out := new(BlinktConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlinktConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlinktConfigList) DeepCopyInto(out *BlinktConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlinktConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlinktConfigList.
func (in *BlinktConfigList) DeepCopy() *BlinktConfigList {
	if in == nil {
		return nil
	}
	out := new(BlinktConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlinktConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlinktConfigSpec) DeepCopyInto(out *BlinktConfigSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Images = in.Images
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(PixelConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlinktConfigSpec.
func (in *BlinktConfigSpec) DeepCopy() *BlinktConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BlinktConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlinktConfigStatus) DeepCopyInto(out *BlinktConfigStatus) {
	*out = *in
	out.Nodes = in.Nodes
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlinktConfigStatus.
func (in *BlinktConfigStatus) DeepCopy() *BlinktConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BlinktConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Images) DeepCopyInto(out *Images) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Images.
func (in *Images) DeepCopy() *Images {
	if in == nil {
		return nil
	}
	out := new(Images)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCounts) DeepCopyInto(out *NodeCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCounts.
func (in *NodeCounts) DeepCopy() *NodeCounts {
	if in == nil {
		return nil
	}
	out := new(NodeCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PixelConfig) DeepCopyInto(out *PixelConfig) {
	*out = *in
	in.PixelConfigSpec.DeepCopyInto(&out.PixelConfigSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PixelConfig.
func (in *PixelConfig) DeepCopy() *PixelConfig {
	if in == nil {
		return nil
	}
	out := new(PixelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PixelConfigSpec) DeepCopyInto(out *PixelConfigSpec) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.Intensity != nil {
		in, out := &in.Intensity, &out.Intensity
		*out = new(int32)
		**out = **in
	}
	if in.Frequency != nil {
		in, out := &in.Frequency, &out.Frequency
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PixelConfigSpec.
func (in *PixelConfigSpec) DeepCopy() *PixelConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PixelConfigSpec)
	in.DeepCopyInto(out)
	return out
}
