#!/usr/bin/env bash
# Render deploy/kubesim-blinkt{,-cdi,-legacy}.yaml from charts/kubesim-blinkt
# with deploy/test-pattern.values.yaml, so the manifests never drift from the chart.
set -euo pipefail
cd "$(dirname "$0")/.."
ns=kubesim-blinkt
for mode in agent cdi legacy; do
  out=deploy/kubesim-blinkt.yaml
  [ "$mode" = agent ] || out=deploy/kubesim-blinkt-$mode.yaml
  case $mode in
    agent)  needs="blinkt-operator in agent mode (BlinktConfig spec.mode: agent)" ;;
    cdi)    needs="blinkt-operator in cdi mode, or dra-driver/deploy (CDI on in containerd)" ;;
    legacy) needs="no DRA: privileged container + hostPath /etc/kubedge" ;;
  esac
  {
    cat <<HDR
# GENERATED by hack/deploy-manifests.sh (make deploy-manifests) from charts/kubesim-blinkt
# with deploy/test-pattern.values.yaml and blinkt.mode=$mode. Do not edit by hand.
#
# Test pattern: one pod per node labelled blinktInstalled=true, all 8 LEDs in distinct
# colours, blinking every 500 ms. Needs: $needs.
#   kubectl label node <node> blinktInstalled=true
#   kubectl apply -f $out
HDR
    if [ "$mode" != legacy ]; then
      echo "# The pod claims all 8 LEDs of its node through DRA: simulator pods asking for a"
      echo "# pixel on the same node stay Pending until this is removed."
    fi
    printf -- '---\napiVersion: v1\nkind: Namespace\nmetadata:\n  name: %s\n' "$ns"
    helm template test-pattern charts/kubesim-blinkt --namespace "$ns" \
      -f deploy/test-pattern.values.yaml --set blinkt.mode="$mode" | sed '/^# Source:/d'
  } > "$out"
  echo "wrote $out"
done
