"""`alemax leaves` — a meta-repo plugin's meta leaf against what ships, file for file.

Meta only: a project has no `scaffolding/`. Until 2026-09-11 nothing compared the shipped
Codex leaf to anything, so a review landed on the meta copy and reached no project. This
is that comparison as a verb any session can run (spec `plugin-leaf-consistency`).

A plugin may declare, in `plugins/<name>/leaves.toml`, the differences its design expects
(scalar keys first — in TOML, keys after a `[[…]]` header belong to that table):

    meta_only_paths = [".agents/.codex-plugin/**"]
    project_only_paths = []
    [[meta_only_blocks]]
    start = "<!-- GENERATED by plugins/opsx/build.py from overlay/preamble"
    end = "---"

Everything that matches a declaration is `expected`; everything else is `drift`.
"""

from __future__ import annotations

import argparse
import difflib
import fnmatch
import sys
import tomllib
from pathlib import Path

from ..io import ERROR, FOUND, OK, die, emit
from ..repo import require_meta


def plugins(root: Path, only: list[str] | None) -> list[str]:
    base = root / "plugins"
    names = sorted(p.name for p in base.iterdir() if (p / "meta").is_dir()) if base.is_dir() else []
    if only:
        missing = set(only) - set(names)
        if missing:
            die(f"no plugin with a meta leaf: {', '.join(sorted(missing))}")
        names = [n for n in names if n in set(only)]
    if not names:
        die("no plugins/<name>/meta/ here")
    return names


def declarations(root: Path, name: str) -> dict:
    f = root / "plugins" / name / "leaves.toml"
    if not f.is_file():
        return {"meta_only_blocks": [], "meta_only_paths": [], "project_only_paths": []}
    d = tomllib.loads(f.read_text(encoding="utf-8"))
    return {
        "meta_only_blocks": d.get("meta_only_blocks", []),
        "meta_only_paths": d.get("meta_only_paths", []),
        "project_only_paths": d.get("project_only_paths", []),
    }


def strip_blocks(text: str, blocks: list[dict]) -> tuple[str, int]:
    """Remove every declared meta-only block (start marker through end marker, inclusive,
    plus one following blank line). Returns the text and how many blocks were removed."""
    removed = 0
    for b in blocks:
        start, end = b["start"], b["end"]
        while True:
            i = text.find(start)
            if i < 0:
                break
            j = text.find("\n" + end, i)
            if j < 0:
                break
            j = text.find("\n", j + 1)
            j = len(text) if j < 0 else j + 1
            # The block is spliced in with its own surrounding blank lines; with it gone,
            # exactly one newline joins what was before it to what follows it.
            text = text[:i].rstrip("\n") + "\n" + text[j:].lstrip("\n")
            removed += 1
    return text, removed


def files_under(base: Path, skip_prefix: str = "") -> dict[str, Path]:
    if not base.is_dir():
        return {}
    out: dict[str, Path] = {}
    for p in sorted(base.rglob("*")):
        if p.is_file() or p.is_symlink():
            rel = str(p.relative_to(base))
            if "/src/" in f"/{rel}" or rel == "src" or rel.startswith("src/"):
                continue  # the vendored package symlink is build.py's concern
            if skip_prefix and rel.startswith(skip_prefix):
                continue
            out[rel] = p
    return out


def pairs(root: Path, name: str) -> list[tuple[str, Path, Path]]:
    """(label, meta_dir, shipped_dir) for each leaf the plugin has on each harness."""
    out: list[tuple[str, Path, Path]] = []
    meta_claude = root / "plugins" / name / "meta" / ".claude"
    if meta_claude.is_dir():
        out.append(("claude", meta_claude, root / "scaffolding" / ".claude" / "skills" / name))
    meta_agents = root / "plugins" / name / "meta" / ".agents" / "skills"
    if meta_agents.is_dir():
        # Everything under the meta .agents root EXCEPT skills/ (a manifest, say) against
        # the shared shipped root — where a project has no such file unless declared.
        out.append(("codex", meta_agents.parent, root / "scaffolding" / ".agents"))
        for skill in sorted(p for p in meta_agents.iterdir() if p.is_dir()):
            out.append(
                (
                    f"codex/{skill.name}",
                    skill,
                    root / "scaffolding" / ".agents" / "skills" / skill.name,
                )
            )
    return out


def edit_here(root: Path, name: str, label: str, rel: str) -> str:
    harness = "claude" if label == "claude" else "codex"
    tpl = root / "plugins" / name / "templates" / harness
    if tpl.is_dir():
        if label == "claude":
            return f"plugins/{name}/templates/claude/{rel}"
        if label == "codex":
            return f"plugins/{name}/templates/codex/{rel}"
        skill = label.split("/", 1)[1]
        return f"plugins/{name}/templates/codex/skills/{skill}/{rel}"
    return f"plugins/{name}/meta/ (this plugin has no templates: the meta leaf is the source)"


def check_plugin(root: Path, name: str) -> list[dict]:
    decl = declarations(root, name)
    findings: list[dict] = []
    for label, meta_dir, ship_dir in pairs(root, name):
        if label.startswith("codex/"):
            prefix = ".agents/skills/" + label.split("/", 1)[1] + "/"
            mfiles, sfiles = files_under(meta_dir), files_under(ship_dir)
        elif label == "codex":
            prefix = ".agents/"
            mfiles = files_under(meta_dir, skip_prefix="skills/")
            sfiles = files_under(ship_dir, skip_prefix="skills/")
        else:
            prefix = ".claude/"
            mfiles, sfiles = files_under(meta_dir), files_under(ship_dir)
        for rel in sorted(set(mfiles) | set(sfiles)):
            full = prefix + rel
            in_m, in_s = rel in mfiles, rel in sfiles
            if in_m and not in_s:
                kind = (
                    "expected"
                    if any(fnmatch.fnmatch(full, g) for g in decl["meta_only_paths"])
                    else "drift"
                )
                findings.append(
                    {
                        "plugin": name,
                        "leaf": label,
                        "path": rel,
                        "kind": kind,
                        "what": "meta only",
                        "edit": edit_here(root, name, label, rel),
                    }
                )
                continue
            if in_s and not in_m:
                kind = (
                    "expected"
                    if any(fnmatch.fnmatch(full, g) for g in decl["project_only_paths"])
                    else "drift"
                )
                findings.append(
                    {
                        "plugin": name,
                        "leaf": label,
                        "path": rel,
                        "kind": kind,
                        "what": "shipped only",
                        "edit": edit_here(root, name, label, rel),
                    }
                )
                continue
            mb, sb_ = mfiles[rel].read_bytes(), sfiles[rel].read_bytes()
            if mb == sb_:
                continue
            try:
                mt, st = mb.decode("utf-8"), sb_.decode("utf-8")
            except UnicodeDecodeError:
                findings.append(
                    {
                        "plugin": name,
                        "leaf": label,
                        "path": rel,
                        "kind": "drift",
                        "what": "binary differs",
                        "edit": edit_here(root, name, label, rel),
                    }
                )
                continue
            stripped, n = strip_blocks(mt, decl["meta_only_blocks"])
            if n and stripped == st:
                findings.append(
                    {
                        "plugin": name,
                        "leaf": label,
                        "path": rel,
                        "kind": "expected",
                        "what": f"{n} declared meta-only block(s)",
                        "edit": "",
                    }
                )
                continue
            diff = "\n".join(
                difflib.unified_diff(
                    st.splitlines(),
                    (stripped if n else mt).splitlines(),
                    f"shipped/{rel}",
                    f"meta/{rel}",
                    lineterm="",
                    n=1,
                )
            )
            findings.append(
                {
                    "plugin": name,
                    "leaf": label,
                    "path": rel,
                    "kind": "drift",
                    "what": "differs",
                    "diff": diff,
                    "edit": edit_here(root, name, label, rel),
                }
            )
    return findings


def cmd_check(a: argparse.Namespace) -> int:
    root = require_meta()
    names = plugins(root, a.plugin or None)
    findings: list[dict] = []
    for n in names:
        findings.extend(check_plugin(root, n))
    drift = [f for f in findings if f["kind"] == "drift"]
    expected = [f for f in findings if f["kind"] == "expected"]
    lines = [f"leaves check: {len(names)} plugin(s), {len(drift)} drift, {len(expected)} expected"]
    if expected:
        lines.append("\nexpected (declared in leaves.toml)")
        for f in expected:
            lines.append(f"  {f['plugin']} {f['leaf']} {f['path']}: {f['what']}")
    if drift:
        lines.append("\ndrift")
        for f in drift:
            lines.append(
                f"  {f['plugin']} {f['leaf']} {f['path']}: {f['what']}  → edit {f['edit']}"
            )
            if f.get("diff"):
                lines.append("    " + f["diff"].replace("\n", "\n    "))
    emit(
        {"plugins": names, "drift": drift, "expected": expected},
        as_json=a.json,
        plain="\n".join(lines),
    )
    if drift and a.strict:
        print(f"leaves check: {len(drift)} drift — refused (--strict)", file=sys.stderr)
        return ERROR
    return FOUND if drift else OK


SUBCOMMANDS = {
    "check": (
        cmd_check,
        "meta leaf vs shipped leaf, per plugin; declared differences apart from drift",
    ),
}


def register(ap: argparse.ArgumentParser) -> None:
    subs = ap.add_subparsers(dest="subcommand", required=True, metavar="SUBCOMMAND")
    for name, (fn, help_text) in SUBCOMMANDS.items():
        sp = subs.add_parser(name, help=help_text)
        sp.add_argument(
            "--plugin",
            action="append",
            help="one plugin (repeatable); default: every plugin with a meta leaf",
        )
        sp.add_argument("--strict", action="store_true", help="exit non-zero on drift")
        sp.add_argument("--json", action="store_true", help="machine-readable output")
        sp.set_defaults(func=fn)
